# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  go:
    container_name: go-app
    image: go-app
    ports: 
      - 8080:8080
    build:
      context: .
    depends_on:
      - postgres

volumes:
  postgres_data: # create the volume for persisting data.
  