apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_PORT: '5432'